server:
   port: 10100
#logging:
   #config: classpath:log4j2.xml

spring:
   application:
      name: config-server
   datasource:
      hikari:
         driver-class-name: net.sf.log4jdbc.DriverSpy
         jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:8066/RUN-TEST?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
         username: root
         password: root


   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 1000  # 连接超时时间（毫秒）